FROM golang:1.16.6-alpine AS builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o unico-challenge main.go

FROM alpine:3.13 AS certs

RUN apk --no-cache add ca-certificates

FROM scratch

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /app/unico-challenge /unico-challenge

EXPOSE 80

ENTRYPOINT [ "/unico-challenge" ]

CMD [ "serve" ]
