version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    image: unico-challenge-app:dev
    container_name: unico-challenge-app
    command: sleep infinity
    working_dir: /app
    volumes:
      - .:/app
      - unico-challenge-vscode-extensions:/home/dev/.vscode-server/extensions
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: unico-challenge-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unico_challenge
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: unico-challenge-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@email.com
      - PGADMIN_DEFAULT_PASSWORD=123
    volumes:
      - ./.docker/pgadmin:/var/lib/pgadmin
    ports:
      - 9000:80
    user: "root:root"

volumes:
  unico-challenge-vscode-extensions:
