CREATE TABLE IF NOT EXISTS feira_livre (
  id SERIAL PRIMARY KEY,
  -- latitude DECIMAL(10,8) NOT NULL,
  -- longitude DECIMAL(11,8) NOT NULL,
  latitude INT NOT NULL,
  longitude INT NOT NULL,
  setor_censitario BIGINT,
  area_ponderacao BIGINT,
  codigo_distrito INT,
  distrito VARCHAR(50),
  codigo_subprefeitura INT,
  subprefeitura VARCHAR(100),
  regiao5 VARCHAR(16),
  regiao8 VARCHAR(16),
  nome_feira VARCHAR(50),
  registro VARCHAR(10),
  logradouro VARCHAR(80),
  -- numero VARCHAR(10),
  numero VARCHAR(30),
  bairro VARCHAR(40),
  referencia VARCHAR(80),
  created_at TIMESTAMPTZ(0) DEFAULT NOW(),
  updated_at TIMESTAMPTZ(0) DEFAULT NOW()
);
