name: Test and Send Coverage Report
on: ["push", "pull_request"]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calc coverage
        run: go list ./... | grep -v /mock | xargs go test -v -covermode=count -coverprofile=cover.out

      - name: Convert go cover to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.2
        with:
            infile: cover.out
            outfile: coverage.lcov

      - name: Send report to coveralls
        uses: coverallsapp/github-action@master
        with:
            github-token: ${{ secrets.github_token }}
            path-to-lcov: coverage.lcov
